### ISSUE TITLE
[3] Resource Management

### ISSUE THREAD

**Issue by sigdelsanjog** [Kathmandu-University-Computer-Club/SFD2017#6]
Managing items required for conducting the events: This requires following resources:
- Projector
- Multi-plug
- Internet
- A StandBy Laptop for presentation
FOOD and Refreshment Includes:
- Tea
- Cookies
- Paper Cups
Volunteer Management
- Call for Volunteers

**Comment by shubham4564** [comment]
Getting TTL will include projectors and and screen, rest should be managed..

**Comment by shubham4564** [comment]
FOSS and Open Source Stickers too,,

**Comment by irigpratit** [comment]
Are we doing a separate event or we are doing the event in collaboration
with FOSS-NP??

On Sep 1, 2017 9:29 AM, "Sanjog Sigdel" <notifications@github.com> wrote:

Assigned #6
<https://github.com/Kathmandu-University-Computer-Club/SFD2017/issues/6> to
@irigpratit <https://github.com/irigpratit>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Kathmandu-University-Computer-Club/SFD2017/issues/6#event-1230708257>,
or mute the thread

**Comment by shubham4564** [comment]
We'll be registering our separate event as KUOSC for SFD 2017, if we can get support from foss-np that would be great!
